apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  strategy: {}
  template:
    metadata:
      labels:
        name: mysql-pod
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-root-password
                name: mysql-secret
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-admin-password
                name: mysql-secret
        envFrom:
            - configMapRef:
                name: mysql-configmap
       
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim
