apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
    mysql-admin-password: VGVjaHBybzEyMzQ=
    mysql-root-password: UjEyMzRy
  # Example:
  # password: {{ .Values.password | b64enc }}