apiVersion: v1
kind: Service
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    app: result-app-pod
  type: NodePort
status:
  loadBalancer: {}
