apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: result-app-pod
    spec:
      containers:
      - image: keziban/resultt:4.0
        name: resultserver
        imagePullPolicy: Always
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-admin-password
                name: mysql-secret
        envFrom:
          - configMapRef:
               name: server-configmap
        ports:
        - containerPort: 80
        resources: {}

