apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook-app-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: phonebook-app-pod
    spec:
      containers:
      - image: keziban/web_server:3.0
        name: webserver
        imagePullPolicy: Always
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-admin-password
                name: mysql-secret
        envFrom:
          - configMapRef:
               name: server-configmap
        ports:
        - containerPort: 80
        resources: {}

